### ISSUE TITLE
Chinese support for a problem

### ISSUE THREAD

**Issue by qianbodong** [timonus/TJDropbox#1]
```
    NSString* path = [NSHomeDirectory() stringByAppendingPathComponent:@"Library/Dropbox 使用入门.pdf"];
    NSLog(@"%@", path);
    [TJDropbox downloadFileAtPath:@"Dropbox 使用入门.pdf" toPath:path accessToken:self.accessToken completion:^(NSDictionary *_Nullable parsedResponse, NSError *_Nullable error) {
        dispatch_async(dispatch_get_main_queue(), ^{
            if (error) {
                NSLog(@"%@ ", [error localizedDescription]);
```

//                    self.outputTextView.text = [error description];
                } else {
                    NSLog(@"OK ");
                }
            });
        }];

  [TJDropbox downloadFileAtPath:@"Dropbox 使用入门.pdf"

or

  [TJDropbox downloadFileAtPath:@"/Dropbox 使用入门.pdf"

All wrong

 The operation couldn’t be completed. (TJDropboxErrorDomain error 0.)

**Comment by timonus** [comment]
I'm looking into this. It looks like Dropbox sends back a 400 with no JSON response info, but the file _does_ actually download successfully. Weird.

**Comment by timonus** [comment]
Ah, take that back, it doesn't work. Investigating.

**Comment by qianbodong** [comment]
To find the cause of the error yet? Thank you

**Comment by timonus** [comment]
Tried a few things, haven't figured it out yet. If you find a solution please let me know!

**Comment by timonus** [comment]
@qianbodong I worked on resolving this today, I just pushed https://github.com/timonus/TJDropbox/commit/382e8653562f9a47646c5842f60f34864da55256 which I think fixes the issue. Can you try it out and let me know?

**Comment by timonus** [comment]
@qianbodong going to close as I think this has been resolved.
