### ISSUE TITLE
Dropbox requests fail with non-ascii encoded paths.  (i.e. unicode characters)

### ISSUE THREAD

**Issue by horseshoe7** [timonus/TJDropbox#10]
I had a user with dropbox files containing the cyrillic alphabet.  (i.e. "/Океан Эльзи - Без бою.txt")

This would fail using the TJDropbox code out of the box.  I found a way to ascii-escape these (well, I also see you have a `asciiEncodedString:` method), but perhaps these should be on every method that has path as an argument?  The out-of-the-box code for `parameterString...` will not ascii-encode these.

I'm wondering what you'd like to do.   You know your code better than I do, so I thought I'd consult first before implementing a definitive fix.  I made it work for my app, but it would be nice to get a universal solution in there...

**Comment by timonus** [comment]
@horseshoe7 thanks for the heads up! I'm planning on trying to fix this. Can you give me some example filenames so I can test this out?

**Comment by horseshoe7** [comment]
Sure thing:  

/Океан Эльзи - Без бою.txt

Will do it.  

I fixed my own local code but it felt hacky and I only did it to solve my own problem, where I think you need it in more places.  I used it just on the upload…. method.  It will fail on download too, but I made a workaround by using the file id: instead of the path.

I’m thinking wherever you use a path variable in the params, you probably need to use your asciiEncodeString: method or whatever it’s called.   Silly me, I made a category method on NSString to do the same thing, not realizing you already had that.

**Comment by timonus** [comment]
Hmm, seems like any path that TJDropbox handles as an input should by run through `-asciiEncodedString:`, which is what it currently does. Sounds like you've come to that conclusion as well. Going to close this, let me know if there's any follow up that should be done!
