### ISSUE TITLE
Chinese support for a problem 2

### ISSUE THREAD

**Issue by qianbodong** [timonus/TJDropbox#12]
Correctly download files contain the Chinese characters

However

Access to get_temporary_link still have errors

I add:
- (Void) getTemporaryLink: (NSString \* const) path accessToken: (NSString \* const) accessToken completion: (void (^ const) (NSDictionary \* _Nullable parsedResponse, NSError \* _Nullable error)) completion
  {
      NSURLRequest \* const request = [self apiRequestWithPath:@"/2/ files/get_temporary_link" accessToken: accessToken parameters: @ {@ "Path": [self asciiEncodeString: path] }];
      [Self performAPIRequest: request withCompletion: completion];
  }

I visited a Chinese called "灯火.mp3" file

Correctly taken to "link" = "https://dl.dropboxusercontent.com/apitl/1/xxx" information.
But https://dl.dropboxusercontent.com/apitl/1/xxx access error Dropbox tips http errorCode 500 error.

The "灯火 .mp3" renamed "cc.mp3" again to get Temporary Link made "link" = "https://dl.dropboxusercontent.com/apitl/1/xxx" information and https: //dl.dropboxusercontent. com/apitl/1/xxx correct data download.

Help, thank you.

**Comment by timonus** [comment]
Hmm, I'm able to reproduce this as well. Seems like it might actually be a Dropbox bug.

**Comment by qianbodong** [comment]
DBRoulette no problem
The key function of Chinese treatment is:
- (NSString_)escapePath:(NSString_)path {
  CFStringEncoding encoding = CFStringConvertNSStringEncodingToEncoding(NSUTF8StringEncoding);
  NSString _escapedPath = 
      (NSString *)CFURLCreateStringByAddingPercentEscapes(kCFAllocatorDefault,
                                                          (CFStringRef)path,
                                                          NULL,
                                                          (CFStringRef)@":?=,!$&'()_+;[]@#~",
                                                          encoding);
  
  return [escapedPath autorelease];
  }

But this process does not work on the api v2, result not_found
