### ISSUE TITLE
not support ipv6?

### ISSUE THREAD

**Issue by qianbodong** [timonus/TJDropbox#2]
iPad running iOS 9.3.2 and iPhone running iOS 9.3.2 on both Wi-Fi and cellular networks

IPv6 network， an error was shown when we attempted to sign in with Dropbox.

“The operation couldn't be completed. (TJDropboxErrorDomain error 0.) ”

**Comment by timonus** [comment]
I'm using all vanilla foundation networking components, which should support IPv6. How are you testing this?

**Comment by qianbodong** [comment]
Apps that exhibit bugs will be rejected

**Comment by qianbodong** [comment]
![temp vsquzqjo](https://cloud.githubusercontent.com/assets/16250993/15751227/eeb689a4-291b-11e6-8588-ff621f168e5d.png)

Apps that exhibit bugs will be rejected

**Comment by timonus** [comment]
Are you sure the bug is due to IPv6? Can you comment with the `userInfo` from the error you're getting? That'll shed more light on what's going on.

**Comment by qianbodong** [comment]
But I can not reproduce.

**Comment by qianbodong** [comment]
My test conditions are restricted, you can help me to test?

**Comment by timonus** [comment]
Yes, can you give me more information about the request you're performing? I can try to repro if I know what you're doing.
