### ISSUE TITLE
Warnings in Xcode 9 ...

### ISSUE THREAD

**Issue by geogerar** [timonus/TJDropbox#27]
Hi...
Many thanks for your excellent tool.....
really it's a fantastic job.
I would like to propose one thing only....
Can you include a better example using all of the possibilities?
Also, with Xcode9 I got some strange warnings like 

"Object of type 'NSDictionary *' is not compatible with dictionary value type 'NSString *"

can you take a look please?

Thank you very much waiting a response from you!

George Gerardis

**Comment by timonus** [comment]
Believe this was resolved in https://github.com/timonus/TJDropbox/commit/983b508486f7e292f6f2a2fff8e0546e2e422741
