### ISSUE TITLE
https://www.dropbox.com Login authentication difference

### ISSUE THREAD

**Issue by qianbodong** [timonus/TJDropbox#3]
TJDropbox

https://www.dropbox.com/1/oauth2/authorize?client_id=xxx&redirect_uri=https://gotoend&response_type=token&force_reapprove=true

Access is very slow, often not open.

DropboxSDK.framework  DBRoulette

https://www.dropbox.com/1/connect_login?k=xxx&s=xxx&state=1B11647A-EDDA-42C6-85A3-C2EAE5888A28&easl=1

Always able to open

In mainland China

why？

**Comment by timonus** [comment]
Was this resolved?
