### ISSUE TITLE
Support new" short-lived" token

### ISSUE THREAD

**Issue by vincechiu** [timonus/TJDropbox#31]
Hi, this is not an issue, but not sure where to request a new feature that Dropbox's "short-lived" token.(https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens) The current not expired token is deprecated and will expire Sep. 2021. 

Thanks for making efforts to make this api for Objective-C. Has been using this lib for a long while.

Thanks!

VC

**Comment by DoctorG** [comment]
Ditto

Greg Moore

**Comment by timonus** [comment]
Hey there, thanks for flagging. I'm aware of this issue but it's going to be a pain in the butt to implement, so haven't started yet 😅. If I do get to it I'll try'n let you know. Two of my apps depend on this library so it's in my best interest to get it working.

**Comment by DoctorG** [comment]
Thanks Tim. You’re the best.

Greg Moore

**Comment by timonus** [comment]
Started working on it here https://github.com/timonus/TJDropbox/tree/refresh-token, it's a long way from done though.

**Comment by DoctorG** [comment]
Thanks!!

Greg Moore

**Comment by timonus** [comment]
Ok, the deadline is growing closer. I need to add support for my apps that use this library. I've started another new branch for this here that I'll be pursuing getting ready for this https://github.com/timonus/TJDropbox/commits/refresh-token-2.

Externally my hope is that the changes are pretty minimal, you'll pass `TJDropboxCredential`s instead of `accessToken` strings to the API calls and the library should just do the rest. 🤞

**Comment by timonus** [comment]
![image](https://user-images.githubusercontent.com/522951/129420746-9c6899cd-f4a7-43ae-800d-d64f4db5fdca.gif)

**Comment by timonus** [comment]
@DoctorG ok, as of 6f293afcad807f942653c2e0ee7c8a50b0d18298 this is working. Haven't merged to master or updated the docs yet, going to live on this in [Close-up](https://apps.apple.com/app/id515789135) for a few days to make sure there are no issues.

**Comment by DoctorG** [comment]
You are awesome Tim.  So appreciate your efforts!

Gregory P. Moore, MD
James River Ob/Gyn
7101 Jahnke Road, Suite 280
Richmond, VA 23225
804-272-5508
JamesRiverObGyn.com

**Comment by timonus** [comment]
Landed the changes on main :)

https://github.com/timonus/TJDropbox/commit/de7fb98371c7ede2a898ac20d11fc8de84d191e5

**Comment by vincechiu** [comment]
@timonus Thx for this update - I'm pulling the branch "https://github.com/timonus/TJDropbox/commits/refresh-token-2", but got some 400 error, wonder there might be something wrong with this new TJDropboxCredential. Wonder do you have updated example how to usethis short-lived token.

**Comment by timonus** [comment]
@vincechiu whoops, think I'm seeing this too. Will troubleshoot and get back to you.

**Comment by timonus** [comment]
Fixed in https://github.com/timonus/TJDropbox/commit/70931a2cf5f8c53d1efdb52b3c1d3e6a6ba8011b
