### ISSUE TITLE
Support refresh tokens when using app auth

### ISSUE THREAD

**Issue by blach** [timonus/TJDropbox#38]
Hello Tim,

thanks a lot for your efforts in adding support for the new short lived tokens and refresh tokens.

It seems however, that TJDropbox's authentication using the iOS Dropbox app doesn't support refresh tokens yet.

I compared what TJDropbox is doing with what the official Dropbox Objective-C SDK is doing, and could enable refresh tokens using TJDropbox and app auth using two simple modifications.

This is an example request from TJDropbox:

`dbapi-2://1/connect?k=9gg2zssmv7XXXXX&s=&state=oauth2code:6Y4vUgu9rIRJbx890ry3mwp2ryhwP0u0FOsaZmMrnx8:S256:&extra_query_params=code_challenge%3D6Y4vUgu9rIRJbx890ry3mwp2ryhwP0u0FOsaZmMrnx8%26code_challenge_method%3DS256%26response_type%3Dcode`

This is an example request from the official Dropbox SDK:

`dbapi-2://1/connect?k=9gg2zssmv7XXXXX&s=&state=oauth2code:kiCBUKN79D3O3hGI_eR0y7zikhTW0R7vY_dD-DeuLf4:S256:offline:account_info.read&extra_query_params=code_challenge%3DkiCBUKN79D3O3hGI_eR0y7zikhTW0R7vY_dD-DeuLf4%26code_challenge_method%3DS256%26token_access_type%3Doffline%26response_type%3Dcode%26scope%3Daccount_info.read`

The notable changes are:

- the `state` parameter adds "offline" after "S256" (See `tokenAccessType` when the state parameter is created in [+[DBOAuthPKCESession createStateWithPkceData:scopeRequest:tokenAccessType:]](https://github.com/dropbox/dropbox-sdk-obj-c/blob/e3a42c1d8c81ec1a291afa3e8e576cf2bf843e05/Source/ObjectiveDropboxOfficial/Shared/Handwritten/OAuth/DBOAuthPKCESession.m#L72)  
- There is an additional `extra_query_params` parameter: `token_access_type=offline`

I added both changes to the URL generated in the `-[TJDropbox dropboxAppAuthenticationURLWithClientIdentifier:codeVerifier:]` method, and could successfully get an access token with a refresh token.

(Actually, just adding "offline" to the state parameter seems to work, but it's better to do the same as the official SDK and do both changes).

**Comment by blach** [comment]
Currently `-[TJDropboxAuthenticationOptions initWithGenerateRefreshToken]` sets the `bypassNativeAuth` to 
yes. Because native auth can indeed generate refresh tokens, I guess this would need to be set to NO instead, too.

Then `-[TJDropbox dropboxAppAuthenticationURLWithClientIdentifier:codeVerifier:]` would have to check if `TJDropboxAuthenticationOptions.generateRefreshToken` is YES, and if so, add the two changes I mentioned above (add `offline` to `state` and add `token_access_type=offline` to  `extra_query_params`).

**Comment by blach** [comment]
This is how the modified method to generate the app auth URL could look like (very similar to `+[TJDropbox tokenAuthenticationURLWithClientIdentifier:redirectURL:codeVerifier:generateRefreshToken:]`):

```objc
+ (NSURL *)dropboxAppAuthenticationURLWithClientIdentifier:(NSString *const)clientIdentifier
                                              codeVerifier:(nullable NSString *const)codeVerifier
                                      generateRefreshToken:(const BOOL)generateRefreshToken
{
    // https://github.com/dropbox/SwiftyDropbox/blob/master/Source/OAuth.swift#L288-L303
    // https://github.com/dropbox/SwiftyDropbox/blob/master/Source/OAuth.swift#L274-L282
    
    NSURLComponents *const components = [NSURLComponents componentsWithString:@"dbapi-2://1/connect"];
    
    NSString *stateString;
    NSString *extraQueryParams = nil;
    if (codeVerifier) {
        NSString *const codeChallenge = _codeChallengeFromCodeVerifier(codeVerifier);
        stateString = [NSString stringWithFormat:@"oauth2code:%@:S256", codeChallenge];
        
        if (generateRefreshToken) {
            stateString = [stateString stringByAppendingString:@":offline"];
        }
        
        NSURLComponents *const extraComponents = [NSURLComponents new];
        
        extraComponents.queryItems = [NSArray arrayWithObjects:
                                      [NSURLQueryItem queryItemWithName:@"code_challenge" value:codeChallenge],
                                      [NSURLQueryItem queryItemWithName:@"code_challenge_method" value:@"S256"],
                                      [NSURLQueryItem queryItemWithName:@"response_type" value:@"code"],
                                      generateRefreshToken ? [NSURLQueryItem queryItemWithName:@"token_access_type" value:@"offline"] : nil,
                                      nil
                                      ];
        extraQueryParams = extraComponents.query;
    } else {
        NSString *const nonce = [[NSUUID UUID] UUIDString];
        stateString = [NSString stringWithFormat:@"oauth2:%@", nonce];
    }
    
    components.queryItems = [NSArray arrayWithObjects:
                             [NSURLQueryItem queryItemWithName:@"k" value:clientIdentifier],
                             [NSURLQueryItem queryItemWithName:@"s" value:@""],
                             [NSURLQueryItem queryItemWithName:@"state" value:stateString],
                             // Following params only apply if verifier is supplied https://bit.ly/37OmYmh
                             extraQueryParams ? [NSURLQueryItem queryItemWithName:@"extra_query_params" value:extraQueryParams] : nil,
                             nil
                             ];
    return components.URL;
}
```

**Comment by timonus** [comment]
Oh yay! I couldn't figure this out but sounds like you did. I'll take a look at integrating this.

**Comment by timonus** [comment]
@blach hmm, I tried myself then literally copy-pasted the code you wrote and still am unable to get refresh tokens in the response. Were there any other changes you made?

**Comment by timonus** [comment]
(also feel free to put up a PR if you have a working version!)

**Comment by blach** [comment]
Did you only look at the URL returned by the Dropbox app? The app does not return a refresh token.

The refresh token is returned by the server in the response to the `/oauth2/token` request made in `+[TJDropbox credentialFromCode:withClientIdentifier:codeVerifier:redirectURL:completion:]`.

**Comment by blach** [comment]
This is how the `parsedResponse` dictionary in the `+[TJDropbox credentialFromCode:withClientIdentifier:codeVerifier:redirectURL:completion:]` method's completion handler looks for me with the changed method I posted above:

```
Printing description of parsedResponse:
{
    "access_token" = "sl.A3boyrba9md...";
    "account_id" = "dbid:AAAYzNWqU...";
    "expires_in" = 14400;
    "refresh_token" = "uufQ_hvArBkAAA...";
    scope = "account_info.read files.content.read files.content.write files.metadata.read files.metadata.write";
    "token_type" = bearer;
    uid = 296640;
}
```

(I redacted the full values)

As you see, it includes the `refresh_token`.

**Comment by blach** [comment]
I've created a PR.

**Comment by timonus** [comment]
> Did you only look at the URL returned by the Dropbox app?

Yep 🙈 I'm dumb, thanks!
