### ISSUE TITLE
Build warnings with XCode 13.0

### ISSUE THREAD

**Issue by Enigma644** [timonus/TJDropbox#40]
Building with XCode 13.0 results in a number of warnings.

* 'UIWebView' is deprecated: first deprecated in iOS 12.0 - No longer supported; please adopt WKWebView.
* Object of type 'NSDictionary *' is not compatible with dictionary value type 'NSString *'
* Object of type 'NSNumber *' is not compatible with dictionary value type 'NSString *'
* Object of type 'NSMutableDictionary *' is not compatible with dictionary value type 'NSString *'

These are just warnings, so everything seems to work just fine, but it'd be really nice to have a clean build :-)

![TjDropox-Compiler-warnings](https://user-images.githubusercontent.com/29318/135656593-bd9dfaaa-7895-4f71-afce-e5b32ef6c2fd.png)

**Comment by timonus** [comment]
I'll work on resolving these but [`TJDropboxAuthenticationViewController` itself is deprecated](https://github.com/timonus/TJDropbox/blob/master/TJDropbox/TJDropboxAuthenticationViewController.h#L20), I'd recommend using `TJDropboxAuthenticator` instead.
