### ISSUE TITLE
get_space_usage parameters

### ISSUE THREAD

**Issue by onfoot** [timonus/TJDropbox#8]
I'm about to use TJDropbox for my app and one of the things I will need is ability to retrieve the amount of free space on user's Dropbox. I implemented the get_space_usage API call, although not without additional changes.

Methods for creating request parameters serialize a `nil` parameter dictionary as an empty POST body, which is probably not valid JSON content, because by the documentation, `get_space_usage` requires a "null" value, which definitely is. I could pass an [NSNull null] parameter, but request methods in the library  accept a <NSString *, NSString *> dictionary.

So, we could either change the [TJDropbox parameterStringForParameters] method to pass "null" in case of a nil dictionary (which I did), or change all request methods to accept an `id` parameter and let `NSJSONSerialization` serialize anything (which I could do, but don't know if such change has any chance of being accepted for a PR).

What do you think?

**Comment by timonus** [comment]
Hmm, I think I'd be ok if you made +parameterStringForParameters param nullable and its return value nullable, and make the +apiRequest... and +contentRequest... "parameters" parameter nullable as well. Should do the trick?

You could alternatively pass an empty dictionary when using that method, which would allow us to keep strict params and still have that endpoint work.

**Comment by onfoot** [comment]
The thing is, both an empty dictionary and empty post body are not accepted. It's pretty strict about it so only "null" is acceptable.

**Comment by timonus** [comment]
Like, literally the string "null"? You could use the API request method with an empty dictionary then manually set the post body to be that string. Would also be good to add a nice large comment for why it's needed, and maybe contact Dropbox mentioning that end point's parameters are whack 😜

**Comment by onfoot** [comment]
Yep! A literal "null" (without quotes). But yeah, it should be able to easily accept an empty dictionary, since a strict JSON parser would probably freak out about an empty string. :)

In my current implementation, the parameterString... method starts with a "null" string instead of a nil value and that Just Works&trade;.

**Comment by timonus** [comment]
I wonder if you could use `NSJSONReadingAllowFragments` in `+parameterStringForParameters:` and make it take `id`.

**Comment by timonus** [comment]
@onfoot are you planning on opening a PR for this? I can take a crack at it if you'd like.

**Comment by onfoot** [comment]
I'm sure `NSJSONReadingAllowFragments` is just for deserializing. It's even a different parameter type.

Finally had some time to explore the API a little further.

Curiously, the curl request provided in call's example works fine:

```
curl -X POST https://api.dropboxapi.com/2/users/get_space_use --header "Authorization: Bearer *TheToken*"
```

But the API explorer suggests this:

```
curl -X POST https://api.dropboxapi.com/2/users/get_space_usage \
--header 'Authorization: Bearer *TheToken*' \
--header 'Content-Type: application/json' \
--data 'null'
```

Which seems sound, because an empty string is not proper JSON, but 'null' is, even though `NSJSONSerialization` doesn't like serializing fragments.

So, after resetting all changes apart from adding the get_space_usage call, I just made one change in `+ (NSURLRequest *)apiRequestWithPath:(NSString *const)path accessToken:(NSString *const)accessToken parameters:(NSDictionary<NSString *, NSString *> *const)parameters`:

```
if (request.HTTPBody != nil) {
    [request addValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
}
```

And the request started working. But that somehow feels wrong and this might be indeed a case for Dropbox to fix the API so it's a little less stringent in terms of accepted parameters.

I'd love to contribute to your library, but you'd have to decide at least what's best for its design. As I got to know the new Dropbox API, it turned out that I'll be needing more stuff, like upload sessions and being able to commit multiple file batches atomically (provided by `/upload_session/finish_batch`) for example. It's great that, as I understand it, you want to keep it as a thin layer over the HTTP API and I think adding other supported calls doesn't break that, so the above change would be just a start. ;)

**Comment by timonus** [comment]
Actually that doesn't seem too bad to me :)

**Comment by onfoot** [comment]
OK then, I'll make the first PR. :)

**Comment by timonus** [comment]
Hey @onfoot, would love it if you'd add the app you're adding TJDropbox to to the [readme](https://github.com/timonus/TJDropbox#apps-using-tjdropbox) if you're comfortable with it 😄

**Comment by onfoot** [comment]
Sure thing, as soon as I introduce the new features using it. :)
